from fastapi import APIRouter
from backend.database import db_manager
from backend.services.model_service import model_service

router = APIRouter(tags=["Health"])


@router.get("/health")
async def health_check():
    """
    Health check endpoint verifying backend connectivity, database status, and ML model readiness.
    """
    db_status = "disconnected"
    if db_manager.db is not None:
        try:
            db_manager.client.admin.command("ping")
            db_status = "connected"
        except Exception:
            db_status = "error"

    model_info = model_service.get_model_status()

    return {
        "status": "healthy",
        "app": "LeafGuard AI",
        "version": "2.0.0",
        "database": db_status,
        "model": model_info,
        "disclaimer": "Predictions are generated by an AI model and may be incorrect. Results should be used as guidance and verified by agricultural professionals when necessary."
    }
