import sys
from pathlib import Path
from contextlib import asynccontextmanager
import logging

# Ensure project root is in sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from fastapi import FastAPI, Request, Depends
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles

from backend.config import settings
from backend.utils.logging_config import setup_logging
from backend.utils.rate_limiter import rate_limit_dependency
from backend.database import db_manager
from backend.services.model_service import model_service

from backend.routes.health import router as health_router
from backend.routes.auth import router as auth_router
from backend.routes.prediction import router as predict_router
from backend.routes.history import router as history_router
from backend.routes.analytics import router as analytics_router

# Initialize structured logging
setup_logging()
logger = logging.getLogger("leafguard.app")


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("🌿 Initializing LeafGuard AI Backend Services...")
    try:
        db_manager.connect()
    except Exception as e:
        logger.warning(f"Database startup warning: {e}")

    # Inspect ML model readiness
    model_status = model_service.get_model_status()
    if model_status["status"] == "ready":
        logger.info(f"✅ ML Model is LIVE (Backend: {model_status['backend']})")
    else:
        logger.warning("⚠️ ML model weight file not found. System is ready for training. (Run 'python training/train_model.py')")

    yield

    db_manager.close()
    logger.info("🛑 LeafGuard AI Backend shutdown complete.")


# Initialize FastAPI application
app = FastAPI(
    title=settings.APP_NAME,
    version=settings.VERSION,
    description="AI-powered plant leaf disease detection and plant health insights platform.",
    openapi_url=f"{settings.API_V1_STR}/openapi.json",
    docs_url=f"{settings.API_V1_STR}/docs",
    redoc_url=None,
    lifespan=lifespan,
    dependencies=[Depends(rate_limit_dependency)]
)

# Configure CORS Middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    logger.exception(f"Unhandled server error at {request.url.path}: {exc}")
    detail = "Internal server error"
    error_msg = str(exc) if settings.DEBUG else "Check server logs for details"
    return JSONResponse(
        status_code=500,
        content={"detail": detail, "error": error_msg}
    )


# ─────────────────────────────────────────────────────────────
# Mount API Routers
# ─────────────────────────────────────────────────────────────
# Mount root-level health check & API V1 routes
app.include_router(health_router)
app.include_router(health_router, prefix=settings.API_V1_STR)

app.include_router(auth_router, prefix=settings.API_V1_STR)
app.include_router(predict_router, prefix=settings.API_V1_STR)
app.include_router(history_router, prefix=settings.API_V1_STR)
app.include_router(analytics_router, prefix=settings.API_V1_STR)

# ─────────────────────────────────────────────────────────────
# Static Mounts
# ─────────────────────────────────────────────────────────────
uploads_dir = Path(__file__).resolve().parent / "uploads"
uploads_dir.mkdir(parents=True, exist_ok=True)
app.mount("/uploads", StaticFiles(directory=str(uploads_dir)), name="uploads")


@app.get("/docs", include_in_schema=False)
def redirect_docs():
    return RedirectResponse(url=f"{settings.API_V1_STR}/docs")


@app.get("/")
def root_status():
    return {
        "app": settings.APP_NAME,
        "version": settings.VERSION,
        "tagline": "AI-powered plant leaf disease detection and plant health insights.",
        "status": "online",
        "docs": f"{settings.API_V1_STR}/docs",
        "disclaimer": "Predictions are generated by an AI model and may be incorrect. Results should be used as guidance and verified by agricultural professionals when necessary."
    }
