"""
LeafGuard AI — Model Evaluation Pipeline
Evaluates the trained EfficientNetB0 plant disease classification model,
calculates Accuracy, Precision, Recall, F1-Score, Confusion Matrix, and saves model_metrics.json.
"""

import os
import sys
import json
import logging
from pathlib import Path
import numpy as np

# Setup paths
TRAINING_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = TRAINING_DIR.parent
BACKEND_MODELS_DIR = PROJECT_ROOT / "backend" / "models"

MODEL_PATH = BACKEND_MODELS_DIR / "plant_disease_model.keras"
CLASSES_PATH = BACKEND_MODELS_DIR / "class_names.json"
METRICS_PATH = BACKEND_MODELS_DIR / "model_metrics.json"

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger("LeafGuardEvalEngine")


def find_eval_dataset_path(root_dir: Path):
    candidate_roots = [
        root_dir / "dataset",
        root_dir / "ml" / "dataset",
        root_dir / "PlantVillage",
    ]
    for root in candidate_roots:
        if not root.exists():
            continue
        for val_name in ["valid", "val", "validation", "test"]:
            cands = list(root.glob(f"**/{val_name}"))
            for c in cands:
                if c.is_dir():
                    return c
        train_cands = list(root.glob("**/train"))
        if train_cands:
            return train_cands[0]
        if root.is_dir():
            return root
    return None


def evaluate():
    import tensorflow as tf
    from sklearn.metrics import classification_report, confusion_matrix, precision_recall_fscore_support, accuracy_score

    logger.info("==================================================")
    logger.info("🌿 LeafGuard AI — Model Evaluation Suite")
    logger.info("==================================================")

    if not MODEL_PATH.exists():
        logger.error(f"❌ Model checkpoint not found at: {MODEL_PATH}")
        logger.error("Please train the model first by running: python training/train_model.py")
        sys.exit(1)

    if not CLASSES_PATH.exists():
        logger.error(f"❌ Class names mapping not found at: {CLASSES_PATH}")
        sys.exit(1)

    with open(CLASSES_PATH, "r", encoding="utf-8") as f:
        class_names = json.load(f)

    eval_path = find_eval_dataset_path(PROJECT_ROOT)
    if not eval_path:
        logger.error(f"❌ Evaluation dataset folder not found under {PROJECT_ROOT / 'dataset'}.")
        sys.exit(1)

    logger.info(f"📁 Loading Evaluation Data from: {eval_path}")
    logger.info(f"📦 Loading Model from: {MODEL_PATH}")

    model = tf.keras.models.load_model(MODEL_PATH, compile=False)

    val_ds = tf.keras.utils.image_dataset_from_directory(
        eval_path,
        image_size=(224, 224),
        batch_size=32,
        shuffle=False,
        label_mode="int"
    )

    y_true = []
    y_pred = []

    logger.info("⚡ Generating predictions on evaluation set...")
    for images, labels in val_ds:
        preds = model.predict(images, verbose=0)
        pred_labels = np.argmax(preds, axis=1)
        y_true.extend(labels.numpy())
        y_pred.extend(pred_labels)

    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    acc = float(accuracy_score(y_true, y_pred))
    precision, recall, f1, _ = precision_recall_fscore_support(y_true, y_pred, average="macro", zero_division=0)

    unique_labels = sorted(list(set(y_true)))
    target_names = [class_names[i] if i < len(class_names) else f"Class_{i}" for i in unique_labels]

    report = classification_report(y_true, y_pred, target_names=target_names, output_dict=True, zero_division=0)
    matrix = confusion_matrix(y_true, y_pred).tolist()

    logger.info("\n" + classification_report(y_true, y_pred, target_names=target_names, zero_division=0))
    logger.info(f"🏆 OVERALL ACCURACY: {acc * 100:.2f}%")
    logger.info(f"🎯 MACRO F1-SCORE:  {f1 * 100:.2f}%")

    metrics_payload = {
        "model_architecture": "EfficientNetB0",
        "num_classes": len(class_names),
        "dataset_path": str(eval_path),
        "metrics": {
            "test_accuracy": round(acc, 4),
            "precision_macro": round(float(precision), 4),
            "recall_macro": round(float(recall), 4),
            "f1_score_macro": round(float(f1), 4)
        },
        "classification_report": report,
        "confusion_matrix": matrix,
        "disclaimer": "Predictions are generated by an AI model and may be incorrect. Results should be used as guidance and verified by agricultural professionals when necessary."
    }

    with open(METRICS_PATH, "w", encoding="utf-8") as f:
        json.dump(metrics_payload, f, indent=2)

    logger.info(f"💾 Metrics successfully exported to: {METRICS_PATH}")


if __name__ == "__main__":
    evaluate()
